"""Settings of the report classification"""

SOURCE_FOLDER = 'source'
LOG_FILE = 'rc.log' 
DB_FILE = 'rc.db3'
REPORT_FOLDER = 'reports' # Store all the reports generated by run_me
STATUS_FILE = 'status.yaml'
MODULE_FOLDER = 'modules'
MOUDLE_SEQUENCE = ['preprocess', 'feature_select', 'classify', 'evaluate', 'error_analyse']